apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: outliersdetector
  namespace: istio-system
spec:
  name: outliersdetector
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: tetewpoj/outliersdetector:latest
          name: outliersdetector
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
          - name: NUMBA_CACHE_DIR # for fix error cannot cache function '_normalise_stats': no locator available for file. library alibi-detect
            value: /tmp/numba_cache
    graph:
      children: []
      name: outliersdetector
      type: MODEL
      endpoint:
        type: REST
    name: outliersdetector
    replicas: 1